### PR TITLE
Rename project to Veriform

### PR DESCRIPTION
**Pull request by tarcieri**
"zser" was not a compelling name.

### CODE REVIEW

**Comment by zmanian** [comment]
Not a fan of new name

**Comment by tarcieri** [comment]
@zmanian lol really? Did you prefer "zser"?

**Comment by zmanian** [comment]
It's not great but at least it communicates it's serialization library.

Miscreant is a brilliant name. Veriform is seems worse...

**Comment by tarcieri** [comment]
@zmanian any suggestions?

**Comment by zmanian** [comment]
`CredibleCredentials`

**Comment by tarcieri** [comment]
Haha, not really a fan of that...

**Pull request merged**
